[build]
  publish = "تطبيق متابعة الاعتمادات/dist"
  command = "cd \"تطبيق متابعة الاعتمادات\" && npm run build"

[[redirects]]
  from = "/n8n-webhook"
  to = "https://n8n.srv968918.hstgr.cloud/webhook/testingemails"
  status = 200
  force = true

[[redirects]]
  from = "/n8n-email-webhook"
  to = "https://n8n.srv968918.hstgr.cloud/webhook/testingemails"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
