[build]
  publish = "follow-up-app/dist"
  command = "python sync_plots.py && cd follow-up-app && npm install && npm run build && cp ../index.html dist/form.html"

[[redirects]]
  from = "/n8n-webhook"
  to = "https://n8n.srv968918.hstgr.cloud/webhook-test/testingemails"
  status = 200
  force = true

[[redirects]]
  from = "/n8n-email-webhook"
  to = "https://n8n.srv968918.hstgr.cloud/webhook-test/testingemails"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
